# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  enabled : false
  replicaCount: 1
app:
  image:
    repository: 
    tag: 
  ingress:
    enabled: true    
  replicaCount : 1
  name: php
  url: app.34.71.70.128.nip.io
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}  

