# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  enabled : false
  replicaCount: 1
app:
  image: 
    repository: gcr.io/k8majutest/phpapp
    tag: 47
  ingress:
    enabled: true    
  replicaCount : 1
  name: php
  url: app.34.71.70.128.nip.io
  resources: 
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"  
  nodeSelector: {}

  tolerations: []

  affinity: {}  

