apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
    APP_NAME: Laravel
    APP_ENV: local
    APP_KEY: base64:RLpD93KpHdyO6xTQlp2vAG25LOaJ7EO60c6OciLX8zg=
    APP_DEBUG: "true"
    APP_URL: http://localhost
    LOG_CHANNEL: stack
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: "3306"
    DB_DATABASE: blog
    DB_USERNAME: root
    DB_PASSWORD: 1234maju
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    QUEUE_CONNECTION: sync
    SESSION_DRIVER: file
    SESSION_LIFETIME: "120"
    REDIS_HOST: "127.0.0.1"
    REDIS_PASSWORD: null
    REDIS_PORT: "6379"
