{{- if .Values.nginx.enabled -}}
#Hide nginx ingress connecting to fast cgi
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: nginx
 annotations:
   kubernetes.io/ingress.class: "nginx"
   external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.url }}
spec:
 rules:
 - host: {{ .Values.app.url }}
   http:
     paths:
     - backend:
         serviceName: nginx
         servicePort: 80

{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-cm
data:
  SCRIPT_FILENAME: "/code/public/index.php"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "example-cm"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.url }}
spec:
  rules:
  - host: {{ .Values.app.url }}
    http:
      paths:
      - backend:
          serviceName: php-service
          servicePort: 9000
{{ end }}
